name: ItemSlotMachine
version: ${project.version}
author: DarkBlade12
website: http://dev.bukkit.org/profiles/DarkBladee12
main: com.darkblade12.itemslotmachine.ItemSlotMachine
api-version: 1.19
softdepend: [Vault, Multiverse-Core, Multiworld, PlotMe, MyWorlds, Essentials]

commands:
  design:
    description: Commands related to designs
    usage: /<command> help
    aliases: [slotdesign, sd]
  coin:
    description: Commands related to coins
    usage: /<command> help
    aliases: [slotcoin, sc]
  slot:
    description: Commands related to slot machines
    usage: /<command> help
    aliases: [slotmachine, sm]
  statistic:
    description: Commands related to statistics
    usage: /<command> help
    aliases: [slotstatistic, stat, stats]